PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username TEXT NOT NULL, hash TEXT NOT NULL, level INTEGER NOT NULL DEFAULT 1);
CREATE TABLE notes (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, note VARCHAR(255) DEFAULT "Note: ", level INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE letters (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, letter TEXT NOT NULL, level INTEGER NOT NULL);
CREATE TABLE addresses (user_id INTEGER NOT NULL, street TEXT NOT NULL, city TEXT NOT NULL, zip TEXT NOT NULL, country TEXT NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE envelopes_modify (user_id INTEGER NOT NULL, modified INTEGER NOT NULL DEFAULT 1, route TEXT, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE recipient_addresses (user_id INTEGER NOT NULL, name TEXT NOT NULL, street TEXT NOT NULL, city TEXT NOT NULL, zip TEXT NOT NULL, country TEXT NOT NULL, level INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE address_book (indx INTEGER NOT NULL, name TEXT NOT NULL, address TEXT NOT NULL, city TEXT NOT NULL, zipcode TEXT NOT NULL, country TEXT NOT NULL);
INSERT INTO address_book VALUES(1,'Lyndhurst Police Department','45 Oakwood Avenue','Lyndhurst','84327','Norton');
INSERT INTO address_book VALUES(2,'Lyndhurst Research Facility','18 Greenwood Drive','Lyndhurst','84330','Norton');
INSERT INTO address_book VALUES(3,'Carinasford DNA Analysis Unit','112 Riverbend Parkway','Carinasford','78219','Norton');
CREATE TABLE inbox (indx INTEGER NOT NULL, name TEXT NOT NULL, address TEXT NOT NULL, city TEXT NOT NULL, zipcode TEXT NOT NULL, country TEXT NOT NULL, time TEXT NOT NULL, message TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "items" (id INTEGER PRIMARY KEY AUTOINCREMENT, item_index INTEGER NOT NULL, level INTEGER NOT NULL, item_type TEXT NOT NULL, item_content TEXT NOT NULL, name TEXT);
INSERT INTO items VALUES(1,1,1,'document','/static/1doc.png','Document');
INSERT INTO items VALUES(2,2,1,'letter','/static/1report.jpg','Report');
INSERT INTO items VALUES(3,3,1,'photograph','/static/1autopsy.jpg','Autopsy');
INSERT INTO items VALUES(4,4,1,'letter','/static/1letter.jpg','Letter');
INSERT INTO items VALUES(8,3,1,'photograph','/static/1key.png','Locker key');
CREATE TABLE IF NOT EXISTS "messages" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, message VARCHAR(1000) NOT NULL, date TIMESTAP, FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS "user_letters" (user_id INTEGER NOT NULL, level INTEGER NOT NULL, message TEXT DEFAULT " ", attachments text default "", FOREIGN KEY (user_id) REFERENCES users(id));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('users',28);
INSERT INTO sqlite_sequence VALUES('letters',3);
INSERT INTO sqlite_sequence VALUES('notes',120);
INSERT INTO sqlite_sequence VALUES('items',8);
INSERT INTO sqlite_sequence VALUES('messages',16);
CREATE UNIQUE INDEX username ON users (username);
CREATE INDEX level  ON notes (level);
CREATE INDEX level2 ON letters (level);
CREATE INDEX level3 ON recipient_addresses (level);
COMMIT;
